openapi: 3.0.0
info:
  title: 'Tasks API'
  version: 1.0.0
servers:
  - url: /api.php
    description: Current host server

paths:
  /tasks.tasks.getList:
    get:
      tags:
        - Таски
      summary: 'Возвращает список тасков по заданному хешу с фильтрацией'
      security:
        - ApiKeyAuth: [ ]
      parameters:
        - in: query
          name: hash
          required: true
          description: |
            основной фильтр (условие) для выборки задач:
            + id/ID - поиск по id таска
            + all - все таски
            + search/TERM - поиск по слову
            + scope/ID - поиск по работе (milestone)
            + project/ID - поиск по проекту
            + inbox - входящие
            + assigned/ID - назначенные на пользователя
            + outbox - исходящие
            + favorites - любименькое
            + urgent
            + hidden - ?
            + creator/ID - создателя
            + contact/ID - ?
            + status/{inprogress|done|ID}
            + unassigned - без исполнителя
            + tag/TAG - поиск по тегу
          schema:
            type: string
            nullable: true
            example: inbox
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'
        - in: query
          name: filters
          description: |
            дополнительный фильтр внутри выборки по hash:
            + assigned_contact_id=1
            + milestone_id=5
            + status_id=-1
            + и т.д
          schema:
            type: string
            nullable: true
            example: assigned_contact_id=1
        - in: query
          name: since
          required: false
          description: вернет таски, обновленные после этого timestamp
          schema:
            type: number
            nullable: true
        - in: query
          name: order
          description: сортировка
          required: false
          schema:
            type: string
            enum:
              - priority
              - oldest
              - newest
              - due
            default: priority
      responses:
        200:
          description: Пагинированный список тасков
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTasksListResponse'
        403:
          description: Запрещено
        500:
          description: Все плохо
  /tasks.statuses.getList:
    get:
      tags:
        - Статусы
      summary: 'Возвращает список статусов'
      security:
        - ApiKeyAuth: [ ]
      responses:
        200:
          description: Список статусов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStatusesListResponse'
        403:
          description: Запрещено
        500:
          description: Все плохо
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: access_token

  schemas:
    getTasksListResponse:
      type: object
      properties:
        total_count:
          type: number
          description: сколько всего тасков найдено
        data:
          type: array
          items:
            $ref: '#/components/schemas/taskInfo'

    getStatusesListResponse:
      type: object
      properties:
        total_count:
          type: number
          description: сколько всего статусов
        data:
          type: array
          items:
            $ref: '#/components/schemas/statusInfo'
    taskInfo:
      type: object
      properties:
        id:
          type: integer
          description: Идентификатор таски
        name:
          type: string
        text:
          type: string
        create_contact:
          $ref: '#/components/schemas/contactInfo'
        visavis_contact:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/contactInfo'
        assigned_contact:
          nullable: true
          allOf:
            - $ref: '#/components/schemas/contactInfo'
        create_datetime:
          type: string
          format: date-time
        update_datetime:
          type: string
          format: date-time
        project_id:
          type: integer
          description: Идентификатор проекта
        milestone_id:
          nullable: true
          type: integer
          description: Идентификатор работы
        number:
          type: integer
          description: Порядковый номер в проекте
        status_id:
          type: integer
          description: Идентификатор статуса
        next_status_id:
          type: integer
          description: Идентификатор следующего по workflow статуса
        parent_id:
          nullable: false
          type: integer
        priority:
          type: integer
        assign_log_id:
          nullable: true
          type: integer
          description: ??
        comment_log_id:
          nullable: true
          type: integer
          description: Идентификатор лога с закрепленным комментарием
        contact_id:
          nullable: true
          type: integer
          description: ???
        hidden_timestamp:
          nullable: true
          type: integer
          description: ???
        due_date:
          type: string
          format: date
          description: Дедлайн
        attachments:
          type: array
        log:
          type: array
        tags:
          type: array
        project:
          $ref: '#/components/schemas/projectInfo'
    projectInfo:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    contactInfo:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    statusInfo:
      type: object
      properties:
        id:
          type: integer
          description: Идентификатор статуса
        name:
          type: string
          description: Название статуса
        button:
          type: string
          description: Текст на кнопке, которая переводит задачу в этот статус. Иногда может совпадать с названием статуса, но чаще всего все-таки является глаголом и поэтому отличается
        special:
          type: boolean
        icon:
          type: string
        icon_url:
          type: string
        icon_class:
          type: string
        icon_html:
          type: string
        sort:
          type: integer
        params:
          $ref: '#/components/schemas/statusParams'
        count:
          $ref: '#/components/schemas/taskCountInfo'
    statusParams:
      type: object
      properties:
        assign_user:
          nullable: true
          type: integer
          description: Новый назначенный пользователь
        button_color:
          nullable: true
          type: string
          description: Цвет фона
        title_color:
          nullable: true
          type: string
          description: Цвет текста
        allow_comment:
          type: boolean
          description: Разрешить комментировать
        allow_clear_assign:
          nullable: true
          type: boolean
          description: Разрешить оставить задачу без назначения
        assign:
          type: string
          enum:
            - "author"
            - "user"
            - "select"
            - ""
          description: |
            Кому назначить таску:
            + "author" - Назначить задачу ее постановщику
            + "user" - Назначить выбранному пользователю
            + "select" - Предлагать выбрать исполнителя
            + "" - Оставить исполнителя без изменения
    taskCountInfo:
      type: object
      description: Содержит информацию о количестве тасков для текущего контекста (статус, проект)
      properties:
        total:
          type: integer
          minimum: 0
          description: Всего тасков
        closed:
          type: integer
          minimum: 0
          description: Всего закрытых тасков
        active:
          type: integer
          minimum: 0
          description: Всего открытых тасков
        active_priority:
          type: integer
          minimum: 0
          description: Всего открытых тасков с высоким приоритетом
  parameters:
    offset:
      in: query
      name: offset
      required: true
      schema:
        type: number
        minimum: 0
    limit:
      in: query
      name: offset
      description: максимальное в ответе. не может быть более 500.
      schema:
        type: number
        nullable: true
        minimum: 0
        default: 30
